### ISSUE TITLE
Members に記載する情報を追加したい

### ISSUE THREAD

**Issue by toshima66** [6vox/6vox.github.io#12]
もう少し説明を追加したい

案
- フルネーム表記
- アイコン表記
- Githubアカウントへのリンク

**Comment by u9r52sld** [comment]
@6vox/staff ホームページにメンバーのアイコンを表示させようと思いますので、みなさんのアイコンの画像をいただけますでしょうか？

**Comment by junki929** [comment]
@u9r52sld あげました。
![icon](https://cloud.githubusercontent.com/assets/4661672/11418549/318993e0-9464-11e5-8c35-792e248a266c.jpg)

**Comment by junki929** [comment]
@u9r52sld 上げ直しました。
![icon2](https://cloud.githubusercontent.com/assets/4661672/11418902/5f251308-9467-11e5-9bab-73e17db97ca5.jpg)

**Comment by murajun1978** [comment]
My avator: https://www.gravatar.com/avatar/d8cd979e90361eb5ca5414dd15b35d0f
