### ISSUE TITLE
Members を最新の情報に更新したい

### ISSUE THREAD

**Issue by toshima66** [6vox/6vox.github.io#17]
新メンバーの追記

**Comment by u9r52sld** [comment]
@toshima66 このissueおそらく終わってると思うんですが、これって僕が削除したりってできますか？

**Comment by toshima66** [comment]
issueは削除するよりcloseする方がよいです。
closeしときます。

**Comment by u9r52sld** [comment]
@toshima66 了解です。ありがとうございます。
