### ISSUE TITLE
gtm.js の 404 に対応

### ISSUE THREAD

**Issue by toshima66** [6vox/6vox.github.io#45]
# 概要
gtm.js が見つからない？

**Comment by toshima66** [comment]
@kyamaguchi81 本件、時間のあるときに調査お願いします。
はやめに対応してもらえるとありがたいです。

**Comment by kyamaguchi81** [comment]
@toshima66 承知致しました。
今から調査致します。

**Comment by kyamaguchi81** [comment]
@toshima66 
調査致しました。
原因は恐らくGoogleタグマネージャーのバージョンを設定していなかった為かと思います。

# 参考URL
https://productforums.google.com/forum/#!topic/tag-manager/w9FeGSsLckY;context-place=forum/tag-manager

私の方で簡単にですがバージョンを設定しまして、「公開」致しまして gtm.js の404エラーのスクリプトエラーが表示されないように対応させて頂きました。

# Googleタグマネージャー: 6vox.com のバージョン設定画面
https://tagmanager.google.com/#/versions/accounts/143120859/containers/1725366/versions/1

## バージョンの設定内容
- バージョン名: バージョン 1
- 説明: 2017/04/09に設定したバージョンです。
※ 変更できます。

## 参考キャプチャ画像
![google_](https://cloud.githubusercontent.com/assets/8565220/24833948/e3e268ae-1d12-11e7-9fd2-74c16614746f.png)

以上となります。
ご確認をよろしくお願いいたします。

**Comment by toshima66** [comment]
@kyamaguchi81 ありがとう。HP上で問題ないことを確認できました。
